name: Manual Workflow Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    
        

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK Setup - openjdk 
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt

      - name: JDK Setup - oraclejdk
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17.0.1 
      
      - name: Install dependencies
        run: mvn -q install -Dgpg.skip

      - name: maven compiling and testing
        run: mvn -q clean compile test

      - name: code coverage on successful build
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
      
      - name: cached maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Notification equivalent for webhook provided
        if: success() 
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"message": "Build successful"}' \
          https://dummyservice.com/webhook-endpoint
          -u ${{ secrets.WEBHOOK_SECRET }}
      


      
      
    

      
          
