name: Manual Workflow Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    
        

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK Setup - openjdk 
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      
      - name: JDK Setup - oraclejdk 
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 11
          java-version: 11
          
