name: Manual Workflow Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    
        

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK Setup - openjdk 
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt

      - name: 'Set up Early-Access build of a named project from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: loom

      
      
    

      
          
