name: Manual Workflow Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    
        

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK Setup - openjdk 
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt

      - name: JDK Setup - oraclejdk
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17.0.1 
      
      - name: Install dependencies
        run: mvn -q install -Dgpg.skip


      
      
    

      
          
