name: Manual Workflow Migration

on:
  push:
    branches:
      - master

jobs:
  build:
    
        

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK Setup - openjdk 
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt

      
      
      
          
